name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    steps:
# Xcode 15.3 not available, abandon this action temporarily
      - name: break
        run: echo "build skipped"

#     - uses: maxim-lobanov/setup-xcode@v1
#       with:
#         xcode-version: latest-stable
#     - uses: swift-actions/setup-swift@v2
#       with: 
#         swift-version: "5.10.0"
#     - uses: actions/checkout@v4
#     - name: Run tests
#       run: swift test
